import type { Metadata } from "next";
import "@/styles/globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "@/components/Footer/Footer";
import HeaderNav from "@/components/HeaderNav/HeaderNav";
import SessionWatcher from "@/components/SessionWatcher/SessionWatcher";
import { SessionProvider } from "next-auth/react";
// import { Nanum_Gothic } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";

config.autoAddCss = false;

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
// export const nanumGothic = Nanum_Gothic({weight:'400', subsets: ["latin"] });

export const metadata: Metadata = {
    title: "simple board",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col justify-between `}>
                {/* <body className={`${nanumGothic.className} antialiased flex flex-col justify-between `} > */}
                <SessionProvider>
                    {/* <SessionWatcher /> */}
                    <HeaderNav /> {/* components에서 관리  */}
                    {/* home 화면만 module.css 로 배경이미지처리, 나머지 화면은 고정 배경색적용 */}
                    <main className="pt-14"> {children} </main>
                    <Footer /> {/* components에서 관리  */}
                </SessionProvider>
            </body>
        </html>
    );
}
