import type { Metadata } from "next";
import "@/styles/globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "@/components/Footer";
import HeaderNav from "@/components/HeaderNav";
import { SessionProvider } from "next-auth/react";
import { Noto_Sans_KR } from "next/font/google";
import DarkModeProvider from "@/components/DarkModeProvider";

config.autoAddCss = false;

const notoSansKr = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "simple board",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${notoSansKr.className} antialiased flex flex-col min-h-screen `}>
                <SessionProvider>
                    <HeaderNav />
                    <DarkModeProvider>
                        <main className="overflow-y-scroll scrollbar-hidden flex-1 ">
                            <div className="max-w-3xl mx-auto ">{children}</div>
                        </main>
                    </DarkModeProvider>
                    <Footer />
                </SessionProvider>
            </body>
        </html>
    );
}
